import { useMemo } from "react";
import { Equal, Expect } from "../../helpers/type-utils";

const Parent = () => {
  const autoGeneratedIds = useMemo<string[]>(() => {
    // generate 100 random string uuid's
    return Array.from({ length: 20 }, () =>
      Math.random().toString(36).substring(2, 10)
    );
  }, []);

  return autoGeneratedIds.map((item, id) => (
    <div className="flex gap-2 my-2 bg-slate-300" key={id}>
      <span className=" bg-black text-white px-3 py-2">{id}</span>
      <p className=" flex-1 text-center justify-center self-center">{item}</p>
    </div>
  ));

  type test = Expect<Equal<typeof autoGeneratedIds, string[]>>;
};

export default Parent;
